// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxV0AuKBwRcarvO3l1rYFUoZzu5dqf85U',
    appId: '1:1020371140475:web:3802674651d406c63487de',
    messagingSenderId: '1020371140475',
    projectId: 'medical-baf76',
    authDomain: 'medical-baf76.firebaseapp.com',
    storageBucket: 'medical-baf76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZO3csqSYkWbU4vzxMR9qdqtrYV5Epc4E',
    appId: '1:1020371140475:android:ce17b0b10d9a9ea33487de',
    messagingSenderId: '1020371140475',
    projectId: 'medical-baf76',
    storageBucket: 'medical-baf76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnVguQqTdFO3ur-2PN4T1_ESTaUzMiw5I',
    appId: '1:1020371140475:ios:30c1487b89609b8a3487de',
    messagingSenderId: '1020371140475',
    projectId: 'medical-baf76',
    storageBucket: 'medical-baf76.firebasestorage.app',
    iosBundleId: 'com.example.libyaMedicalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnVguQqTdFO3ur-2PN4T1_ESTaUzMiw5I',
    appId: '1:1020371140475:ios:30c1487b89609b8a3487de',
    messagingSenderId: '1020371140475',
    projectId: 'medical-baf76',
    storageBucket: 'medical-baf76.firebasestorage.app',
    iosBundleId: 'com.example.libyaMedicalMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxV0AuKBwRcarvO3l1rYFUoZzu5dqf85U',
    appId: '1:1020371140475:web:614320b7a9b79eea3487de',
    messagingSenderId: '1020371140475',
    projectId: 'medical-baf76',
    authDomain: 'medical-baf76.firebaseapp.com',
    storageBucket: 'medical-baf76.firebasestorage.app',
  );
}
